
//GIVEN VARIABLES AND FUNCTIONS IN CHAPTER (with my explanations)

var roads = [
    "Alice's House-Bob's House",
    "Alice's House-Cabin",
    "Alice's House-Post Office",
    "Bob's House-Town Hall",
    "Daria's House-Ernie's House",
    "Daria's House-Town Hall",
    "Ernie's House-Grete's House",
    "Grete's House-Farm",
    "Grete's House-Shop",
    "Marketplace-Farm",
    "Marketplace-Post Office",
    "Marketplace-Shop",
    "Marketplace-Town Hall",
    "Shop-Town Hall"
  ];
  
  function buildGraph(edges) {            //edges input is roads variable above
    let graph = Object.create(null);      //empty object with no inherited properties as opposed to {} which inherits Object.prototype
    function addEdge(from, to) {        //from and to taken from var roads are inputs (see for loop below)
      if (graph[from] == null) {        //if the graph doesn't have the property "from" it creates the property "to"
        graph[from] = [to]; 
      } else {                        //if the graph has the property "from" it pushes "to"
        graph[from].push(to);
      }
    }
    for (let [from, to] of edges.map(r => r.split("-"))) { //uses .map to create array and .split to separate "Start-End" format to [from, to] and iterates through roads variable
      addEdge(from, to);             //runs addEdge functions with parameters switched to iterate through every connection 
      addEdge(to, from);            // property "from" ends up with "to" as a value,  and property "to" ends up with "from" as a value
    }
    return graph;
  }
  
  var roadGraph = buildGraph(roads);  //console.log(roadGraph); //this is object with each .place as property with value = [] places it touches
  
  var VillageState = class VillageState {  
    constructor(place, parcels) {         //simply the constructor which gets called at the end of VillageState.random initally
      this.place = place;                 //and gets called at the end of state.move() 
      this.parcels = parcels;
    }
    move(destination) {
      if (!roadGraph[this.place].includes(destination)) {   
        return this;           // checks whether there is a road going from the current place to the destination, and if not, it returns the old state since this is not a valid move
      } else {
        let parcels = this.parcels
          .map(p => {   
            if (p.place != this.place) return p;    // I don't know why this line exists and it works without it
            return { place: destination, address: p.address };  //this maps a new array of objects(parcels) with the place = destination(where the robot is moving to)
          })
          .filter(p => p.place != p.address);               // filters out objects where the place and address are equal (dropping off parcels)
        return new VillageState(destination, parcels);       // returns new class (state) with updated destination (state.place) and parcels (state.parcels)
      }
    }
  };
  
  function runRobot(state, robot, memory) {
    for (let turn = 0; ; turn++) {            //iterates forever until there are no objects in parcels array
      if (state.parcels.length == 0) {
          //console.log(`Done in ${turn} turns.`);
        return turn;
        break;
      }
      let action = robot(state, memory);
      state = state.move(action.direction);   // robot's .direction and .memory are generated by type of robot function, input into VillageState.move()
      memory = action.memory;             // robot's .memory is mailRoute or findRoute()
      //console.log(`Moved to ${action.direction}`);
      //console.log(action);    //object with direction and memory, unless its randomRobot which has no memory
      //console.log(memory);
      //console.log(state);   // object with properties parcels (array of objects) and place (string)
    }
  }
  
  function randomPick(array) {
    let choice = Math.floor(Math.random() * array.length);      //this picks a random value within an array
    return array[choice];
  }
  
  function randomRobot(state) {
    return { direction: randomPick(roadGraph[state.place]) };   // chooses random value of current state.place property in roadGraph
  }
  
  //THIS IS THE STARTING STATE
  VillageState.random = function(parcelCount = 5) {         //the map starts with # parcels
    let parcels = [];
    for (let i = 0; i < parcelCount; i++) {
      let address = randomPick(Object.keys(roadGraph));   //sets random Object.keys of roadGraph (location) as parcel address
      let place;
      do {
        place = randomPick(Object.keys(roadGraph));       //sets random Object.keys of roadGraph (location) as parcel place
      } while (place == address);                         //loops so place and address don't start out the same
      parcels.push({ place, address });                   //adds object with place and address properties to array parcels
    }
    return new VillageState("Post Office", parcels);      //robot starts at Post Office, parcels start in random locations
  };
  
  var mailRoute = [
    "Alice's House",
    "Cabin",
    "Alice's House",
    "Bob's House",
    "Town Hall",
    "Daria's House",
    "Ernie's House",
    "Grete's House",
    "Shop",
    "Grete's House",
    "Farm",
    "Marketplace",
    "Post Office"
  ];
  
  function routeRobot(state, memory) {
    if (memory.length == 0) {
      memory = mailRoute;     //resets the memory to go around the route again
    }
    return { direction: memory[0], memory: memory.slice(1) };  // sets direction to next in memory array and removes that from the array
  }
  
  function findRoute(graph, from, to) {   //from is current robot.place, to is either parcels.place or parcels.address
    let work = [{ at: from, route: [] }];
    for (let i = 0; i < work.length; i++) {
      let { at, route } = work[i];
      for (let place of graph[at]) {      //iterates through values of roadGraph's property(robot's current location)
        if (place == to) return route.concat(place);    //if one of the values matches parcel's (either place or address) it's added to route
        if (!work.some(w => w.at == place)) {   // if no object in work array has .at value equal to place
          work.push({ at: place, route: route.concat(place) });  // add new object to work array 
        }
      } //console.log(work);
    } 
  }
  
  function goalOrientedRobot({ place, parcels }, route) {   //in runRobot function, robot (state, memory), {place, parcels} = state, route = memory
    if (route.length == 0) {
      let parcel = parcels[0];    //starts with first parcel robot has
      if (parcel.place != place) {      //if the parcel was not just picked up at the current place
        route = findRoute(roadGraph, place, parcel.place);    //run findRoute with to = parcel's current place
      } else {
        route = findRoute(roadGraph, place, parcel.address);  // if the parcel's current place is robots place, findRoute with parcel's address (where its going)
      }
    } //console.log(route);
    return { direction: route[0], memory: route.slice(1) }; //direction = first value in roadGraph's from(robot's current location), memory = removes first item from the array. when array is empty above code executes.
  }
  

  //runRobot(VillageState.random(), randomRobot); 
  //runRobot(VillageState.random(), routeRobot, []);
  //runRobot(VillageState.random(), goalOrientedRobot, []); 
  
  //console.log(roadGraph)
  

  //COMPARE ROBOTS SOLITION
  
  function compareRobots(robot1, memory1, robot2, memory2, robot3, parcels=5){
    let robot1Turns = 0;
    let robot2Turns = 0;
    let robot3Turns = 0;
    for (i=0;i<100;i++){
      robot1Turns += runRobot(VillageState.random(parcels), robot1, memory1);
      robot2Turns += runRobot(VillageState.random(parcels), robot2, memory2);
      robot3Turns += runRobot(VillageState.random(parcels), robot3);
    }
    console.log("Starting with " + parcels + " parcels:\n" + robot1.name + ": " + robot1Turns + ", " + robot2.name + ": " + robot2Turns + ", " + robot3.name + ": " + robot3Turns + ".");
  }
  
  compareRobots(routeRobot, [], goalOrientedRobot, [], randomRobot, 50);